### ISSUE TITLE
Can the model be used for real world outdoor UGV?

### ISSUE THREAD

**Issue by poornimajd** [abhiksingla/UAV_obstacle_avoidance_controller#2]
Hello
Great work! I would like to know if the proposed algorithm can be used for outdoor real world environments by training it with the appropriate monocular images. I also have the depth maps generated for the same.Can I use the network for a ugv on indian roads?
Thank you

**Comment by abhiksingla** [comment]
Hi,
In principle, the algorithm should work outside after finetuning with outdoor depth images. We have had plans to test in the real world, before strict government regulations on drones.

**Comment by poornimajd** [comment]
Thank you for the response.I will look into the finetuning part with my images.
